run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt

linters-settings:
  gofumpt:
    extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
